# Lista 3 - Sistemas de Equação

## Importando os pacotes

In [1]:
from methods.straightforward_methods import *
from numpy.typing import NDArray
import pandas as pd
import numpy as np

In [ ]:
# MATRIZ ORIGINAL
# [ 5,291 −6,130    ]
# [ 0,0   59,14     ]
#
# VETOR INDEPENDENTE
# [ 46,78   59,14   ]

matriz_aumentada:NDArray = np.matrix([[5.291, -6.13, 46.78],
                                     [0.0, 59.14, 59.14]],
                                     dtype=np.float64)

matriz_aumentada

In [ ]:
gaussian_elimination(matriz_aumentada.copy())

In [ ]:
gaussian_elimination_partial_pivoting(matriz_aumentada.copy())

In [2]:
matriz_exemplo:NDArray = np.matrix([[-2.0, 2.2, 6.0],
                                    [1.5, -1.0, 0.5],
                                    [2.0, 5.0, 7.0]], dtype=np.float64)
matriz_exemplo

matrix([[-2. ,  2.2,  6. ],
        [ 1.5, -1. ,  0.5],
        [ 2. ,  5. ,  7. ]])

In [3]:
LU_factoring(matriz_exemplo.copy())

(array([[ 1.        ,  0.        ,  0.        ],
        [-0.75      ,  1.        ,  0.        ],
        [-1.        , 11.07692308,  1.        ]]),
 array([[ -2.        ,   2.2       ,   6.        ],
        [  0.        ,   0.65      ,   5.        ],
        [  0.        ,   0.        , -42.38461538]]))