# Testes dos algoritmos

## Importando os pacotes

In [1]:
from methods.straightforward_methods import *
from methods.iterative_methods import *
from numpy.typing import NDArray
import pandas as pd
import numpy as np

## Métodos Diretos

In [2]:
matriz_exemplo:NDArray = np.matrix([[5.291, -6.13],
                                    [0.0, 59.14]], dtype=np.float64)
vetor_solucao:NDArray = np.array([46.78, 59.14], dtype=np.float64)
matriz_aumentada:NDArray = np.concatenate((matriz_exemplo, vetor_solucao.reshape(-1, 1)), axis=1)
matriz_aumentada

matrix([[ 5.291, -6.13 , 46.78 ],
        [ 0.   , 59.14 , 59.14 ]])

In [3]:
gaussian_elimination(matriz_aumentada.copy())

array([10.,  1.])

In [4]:
gaussian_elimination_partial_pivoting(matriz_aumentada.copy())

array([10.,  1.])

In [5]:
gaussian_elimination_partial_pivoting_scaled(matriz_aumentada.copy())

array([10.,  1.])

In [6]:
gaussian_elimination_full_pivoting(matriz_aumentada.copy())

array([ 1., 10.])

In [7]:
matriz_exemplo:NDArray = np.matrix([[1.0, 1.0, 0.0, 3.0],
                                    [2.0, 1.0, -1.0, 1.0],
                                    [3.0, -1.0, -1.0, 2.0],
                                    [-1.0, 2.0, 3.0, -1.0]], dtype=np.float64)
matriz_exemplo

matrix([[ 1.,  1.,  0.,  3.],
        [ 2.,  1., -1.,  1.],
        [ 3., -1., -1.,  2.],
        [-1.,  2.,  3., -1.]])

In [8]:
LU_factoring(matriz_exemplo.copy())

(array([[ 1.,  0.,  0.,  0.],
        [ 2.,  1.,  0.,  0.],
        [ 3.,  4.,  1.,  0.],
        [-1., -3.,  0.,  1.]]),
 array([[  1.,   1.,   0.,   3.],
        [  0.,  -1.,  -1.,  -5.],
        [  0.,   0.,   3.,  13.],
        [  0.,   0.,   0., -13.]]))

## Métodos iterativos

In [9]:
matriz_exemplo:NDArray = np.matrix([[6.0, -1.0, 3.0],
                                    [1.0, 3.0, 1.0],
                                    [3.0, -1.0, 5.0]], dtype=np.float64)
vetor_solucao:NDArray = np.array([13.0, 10.0, 16.0], dtype=np.float64)
matriz_aumentada:NDArray = np.concatenate((matriz_exemplo, vetor_solucao.reshape(-1, 1)), axis=1)
max_iter:int = 30
tol:np.float64 = np.float64(0.01) # <-- 1 % de tolerancia

matriz_aumentada

matrix([[ 6., -1.,  3., 13.],
        [ 1.,  3.,  1., 10.],
        [ 3., -1.,  5., 16.]])

In [10]:
jacobi(matriz_aumentada, tol, max_iter)

RuntimeError: ('O método de Jacobi não convergiu após ', 30, ' iterações.')