# Testes dos algoritmos


## Importando os pacotes


In [1]:
from straightforward_methods import (
    naive_gauss,
    gauss_partial_pivoting,
    gauss_scaled_pivoting,
    gauss_complete_pivoting,
    LU_solve,
)

from numpy.typing import NDArray
import pandas as pd
import numpy as np

## Métodos Diretos

### Gauss métodos

In [2]:
A: NDArray = np.matrix([[0.003, 59.14],
                                     [5.291, -6.130]], dtype=np.float64)
""" A: NDArray = np.matrix([[3, -0.1, -0.2],
                                     [0.1, 7, -0.3],
                                     [0.3, -0.2, 10]], dtype=np.float64)
B: NDArray = np.array([7.85, -19.3, 71.4], dtype=np.float64) """
B: NDArray = np.array([59.17, 46.78], dtype=np.float64)

A_augmented: NDArray = np.concatenate(
    (A, B.reshape(-1, 1)), axis=1
)
A_augmented

matrix([[ 3.000e-03,  5.914e+01,  5.917e+01],
        [ 5.291e+00, -6.130e+00,  4.678e+01]])

In [3]:
methods = {
    "Naive Gauss": naive_gauss,
    "Gauss Partial Pivoting": gauss_partial_pivoting,
    "Gauss Scaled Pivoting": gauss_scaled_pivoting,
    "Gauss Complete Pivoting": gauss_complete_pivoting,
}

results_columns = [f"x_{i}" for i in range(A_augmented.shape[1] - 1)]
df_result = pd.DataFrame(
    data={
        "Method": [],
        **{
            f"x_{i}": []
            for i in range(A_augmented.shape[1] - 1)
        },
    }
)

for method_name, method in methods.items():

    result = method(A_augmented.copy())

    # Append the results to the DataFrame
    tmp_df = pd.DataFrame(
        data={
            "Method": [method_name],
            **{
                f"x_{i}": result[i]
                for i in range(result.shape[0])
            },
        }
    )

    df_result = pd.concat([df_result, tmp_df], ignore_index=True)

df_result

Method   x_0  x_1
0              Naive Gauss  10.0  1.0
1   Gauss Partial Pivoting  10.0  1.0
2    Gauss Scaled Pivoting  10.0  1.0
3  Gauss Complete Pivoting  10.0  1.0

### Fatoração LU

In [4]:
A: NDArray = np.matrix(
    [
        [1.0, 1.0, 0.0, 3.0],
        [2.0, 1.0, -1.0, 1.0],
        [3.0, -1.0, -1.0, 2.0],
        [-1.0, 2.0, 3.0, -1.0],
    ],
    dtype=np.float64,
)

B: NDArray = np.array([4.0, 1.0, -3.0, 4.0], dtype=np.float64)

A_augmented: NDArray = np.concatenate(
    (A, B.reshape(-1, 1)), axis=1
)

A_augmented

matrix([[ 1.,  1.,  0.,  3.,  4.],
        [ 2.,  1., -1.,  1.,  1.],
        [ 3., -1., -1.,  2., -3.],
        [-1.,  2.,  3., -1.,  4.]])

In [5]:
x = LU_solve(A_augmented.copy())

x

array([-1.,  2.,  0.,  1.])

## Métodos iterativos


In [6]:
""" example_matrix: NDArray = np.matrix(
    [[6.0, -1.0, 3.0], [1.0, 3.0, 1.0], [3.0, -1.0, 5.0]], dtype=np.float64
)
target_values: NDArray = np.array([13.0, 10.0, 16.0], dtype=np.float64)
augmented_matrix: NDArray = np.concatenate(
    (example_matrix, target_values.reshape(-1, 1)), axis=1
)
max_iter: int = 20
tol: np.float64 = np.float64(0.001)  # <-- 0,1 % de tolerancia

augmented_matrix

jacobi(augmented_matrix.copy(), tol, max_iter)
gauss_seidel(augmented_matrix.copy(), tol, max_iter)
relaxing(augmented_matrix.copy(), tol, max_iter, np.float64(1.12)) """

' example_matrix: NDArray = np.matrix(\n    [[6.0, -1.0, 3.0], [1.0, 3.0, 1.0], [3.0, -1.0, 5.0]], dtype=np.float64\n)\ntarget_values: NDArray = np.array([13.0, 10.0, 16.0], dtype=np.float64)\naugmented_matrix: NDArray = np.concatenate(\n    (example_matrix, target_values.reshape(-1, 1)), axis=1\n)\nmax_iter: int = 20\ntol: np.float64 = np.float64(0.001)  # <-- 0,1 % de tolerancia\n\naugmented_matrix\n\njacobi(augmented_matrix.copy(), tol, max_iter)\ngauss_seidel(augmented_matrix.copy(), tol, max_iter)\nrelaxing(augmented_matrix.copy(), tol, max_iter, np.float64(1.12)) '