# Testes dos algoritmos


## Importando os pacotes


In [1]:
from direct_methods import (
    naive_gauss,
    gauss_partial_pivoting,
    gauss_scaled_pivoting,
    gauss_complete_pivoting,
    LU_solve,
)

from iterative_methods import (
    jacobi,
    gauss_seidel,
    relaxing,
)

from numpy.typing import NDArray
import pandas as pd
import numpy as np

## Métodos Diretos


### Gauss métodos


In [2]:
A: NDArray = np.matrix([[0.003, 59.14], [5.291, -6.130]], dtype=np.float64)
""" A: NDArray = np.matrix([[3, -0.1, -0.2],
                                     [0.1, 7, -0.3],
                                     [0.3, -0.2, 10]], dtype=np.float64)
B: NDArray = np.array([7.85, -19.3, 71.4], dtype=np.float64) """
B: NDArray = np.array([59.17, 46.78], dtype=np.float64)

A_augmented: NDArray = np.concatenate((A, B.reshape(-1, 1)), axis=1)
A_augmented

matrix([[ 3.000e-03,  5.914e+01,  5.917e+01],
        [ 5.291e+00, -6.130e+00,  4.678e+01]])

In [3]:
methods = {
    "Naive Gauss": naive_gauss,
    "Gauss Partial Pivoting": gauss_partial_pivoting,
    "Gauss Scaled Pivoting": gauss_scaled_pivoting,
    "Gauss Complete Pivoting": gauss_complete_pivoting,
}

results_columns = [f"x_{i}" for i in range(A_augmented.shape[1] - 1)]
df_result = pd.DataFrame(
    data={
        "Method": [],
        **{f"x_{i}": [] for i in range(A_augmented.shape[1] - 1)},
    }
)

for method_name, method in methods.items():
    result = method(A_augmented.copy())

    # Append the results to the DataFrame
    tmp_df = pd.DataFrame(
        data={
            "Method": [method_name],
            **{f"x_{i}": result[i] for i in range(result.shape[0])},
        }
    )

    df_result = pd.concat([df_result, tmp_df], ignore_index=True)

df_result

Method   x_0  x_1
0              Naive Gauss  10.0  1.0
1   Gauss Partial Pivoting  10.0  1.0
2    Gauss Scaled Pivoting  10.0  1.0
3  Gauss Complete Pivoting  10.0  1.0

### Fatoração LU


In [4]:
A: NDArray = np.matrix(
    [
        [1.0, 1.0, 0.0, 3.0],
        [2.0, 1.0, -1.0, 1.0],
        [3.0, -1.0, -1.0, 2.0],
        [-1.0, 2.0, 3.0, -1.0],
    ],
    dtype=np.float64,
)

B: NDArray = np.array([4.0, 1.0, -3.0, 4.0], dtype=np.float64)

A_augmented: NDArray = np.concatenate((A, B.reshape(-1, 1)), axis=1)

A_augmented

matrix([[ 1.,  1.,  0.,  3.,  4.],
        [ 2.,  1., -1.,  1.,  1.],
        [ 3., -1., -1.,  2., -3.],
        [-1.,  2.,  3., -1.,  4.]])

In [5]:
x = LU_solve(A_augmented.copy())

x

array([-1.,  2.,  0.,  1.])

## Métodos iterativos


In [6]:
A: NDArray = np.matrix(
    [[6.0, -1.0, 3.0], [1.0, 3.0, 1.0], [3.0, -1.0, 5.0]], dtype=np.float64
)

B: NDArray = np.array([13.0, 10.0, 16.0], dtype=np.float64)

A_augmented: NDArray = np.concatenate((A, B.reshape(-1, 1)), axis=1)
max_iter: int = 20
tol: np.float64 = np.float64(0.001)  # <-- 0,1 % de tolerancia

A_augmented

matrix([[ 6., -1.,  3., 13.],
        [ 1.,  3.,  1., 10.],
        [ 3., -1.,  5., 16.]])

In [7]:
methods = {
    "Jacobi": jacobi,
    "Gauss-Seidel": gauss_seidel,
    "Relaxing": relaxing,
}

df_result = pd.DataFrame(
    data={
        "Method": [],
        **{f"x_{i}": [] for i in range(A_augmented.shape[1] - 1)},
    }
)

for method_name, method in methods.items():
    if method_name == "Relaxing":
        result = method(A_augmented.copy(), tol, max_iter, np.float64(1.12))
    else:
        result = method(A_augmented.copy(), tol, max_iter)

    # Append the results to the DataFrame
    tmp_df = pd.DataFrame(
        data={
            "Method": [method_name],
            **{f"x_{i}": result[i] for i in range(result.shape[0])},
        }
    )

    df_result = pd.concat([df_result, tmp_df], ignore_index=True)
df_result

Method       x_0       x_1       x_2
0        Jacobi  1.000319  2.000080  2.999825
1  Gauss-Seidel  1.000319  2.000080  2.999825
2      Relaxing  1.000014  2.000205  3.000072