# Testes dos algoritmos


## Importando os pacotes


In [1]:
from straightforward_methods import (
    naive_gauss,
    gauss_partial_pivoting,
    gauss_scaled_pivoting,
    gauss_complete_pivoting,
    LU_factoring
)

from straightforward_methods_2 import (
    naive_gauss as naive_gauss_2,
    gauss_partial_pivoting as gauss_partial_pivoting_2,
    partial_pivoting_decorator
)

from numpy.typing import NDArray
import pandas as pd
import numpy as np

## Métodos Diretos

In [2]:
example_matrix: NDArray = np.matrix([[5.291, -6.13], [0.0, 59.14]], dtype=np.float64)
target_values: NDArray = np.array([46.78, 59.14], dtype=np.float64)
augmented_matrix: NDArray = np.concatenate(
    (example_matrix, target_values.reshape(-1, 1)), axis=1
)
augmented_matrix

matrix([[ 5.291, -6.13 , 46.78 ],
        [ 0.   , 59.14 , 59.14 ]])

### Igor Métodos

In [3]:
methods = {
    "Naive Gauss": naive_gauss,
    "Gauss Partial Pivoting": gauss_partial_pivoting,
    "Gauss Scaled Pivoting": gauss_scaled_pivoting,
    "Gauss Complete Pivoting": gauss_complete_pivoting,
}

results_columns = [f"x_{i}" for i in range(augmented_matrix.shape[1] - 1)]
df_result = pd.DataFrame(
    data={
        "Method": [],
        **{
            f"x_{i}": []
            for i in range(augmented_matrix.shape[1] - 1)
        },
    }
)

for method_name, method in methods.items():
    # Measure the time taken by each method
    result = method(augmented_matrix.copy())

    # Append the results to the DataFrame
    tmp_df = pd.DataFrame(
        data={
            "Method": [method_name],
            **{
                f"x_{i}": result[i]
                for i in range(result.shape[0])
            },
        }
    )

    df_result = pd.concat([df_result, tmp_df], ignore_index=True)

df_result

Method   x_0   x_1
0              Naive Gauss  10.0   1.0
1   Gauss Partial Pivoting  10.0   1.0
2    Gauss Scaled Pivoting  10.0   1.0
3  Gauss Complete Pivoting   1.0  10.0

### Matheus Métodos

In [4]:
methods = {
    "Naive Gauss": naive_gauss_2,
    "Gauss Partial Pivoting": gauss_partial_pivoting_2,
    #"Gauss Scaled Pivoting": gauss_scaled_pivoting,
    #"Gauss Complete Pivoting": gauss_complete_pivoting,
}

results_columns = [f"x_{i}" for i in range(augmented_matrix.shape[1] - 1)]
df_result = pd.DataFrame(
    data={
        "Method": [],
        **{
            f"x_{i}": []
            for i in range(augmented_matrix.shape[1] - 1)
        },
    }
)

for method_name, method in methods.items():
    # Measure the time taken by each method
    n: int = augmented_matrix.shape[0]
    a: NDArray = augmented_matrix[::, :-1].copy()
    b: NDArray = augmented_matrix[::, -1].copy()

    result = method(a, b)

    # Append the results to the DataFrame
    tmp_df = pd.DataFrame(
        data={
            "Method": [method_name],
            **{
                f"x_{i}": result[i]
                for i in range(result.shape[0])
            },
        }
    )

    df_result = pd.concat([df_result, tmp_df], ignore_index=True)

df_result

Antes da função
Depois da função


Method   x_0  x_1
0             Naive Gauss  10.0  1.0
1  Gauss Partial Pivoting  10.0  1.0

In [5]:
example_matrix: NDArray = np.matrix(
    [
        [1.0, 1.0, 0.0, 3.0],
        [2.0, 1.0, -1.0, 1.0],
        [3.0, -1.0, -1.0, 2.0],
        [-1.0, 2.0, 3.0, -1.0],
    ],
    dtype=np.float64,
)
example_matrix

matrix([[ 1.,  1.,  0.,  3.],
        [ 2.,  1., -1.,  1.],
        [ 3., -1., -1.,  2.],
        [-1.,  2.,  3., -1.]])

In [6]:
LU_factoring(example_matrix.copy())

(array([[ 1.,  0.,  0.,  0.],
        [ 2.,  1.,  0.,  0.],
        [ 3.,  4.,  1.,  0.],
        [-1., -3.,  0.,  1.]]),
 array([[  1.,   1.,   0.,   3.],
        [  0.,  -1.,  -1.,  -5.],
        [  0.,   0.,   3.,  13.],
        [  0.,   0.,   0., -13.]]))

## Métodos iterativos


In [7]:
""" example_matrix: NDArray = np.matrix(
    [[6.0, -1.0, 3.0], [1.0, 3.0, 1.0], [3.0, -1.0, 5.0]], dtype=np.float64
)
target_values: NDArray = np.array([13.0, 10.0, 16.0], dtype=np.float64)
augmented_matrix: NDArray = np.concatenate(
    (example_matrix, target_values.reshape(-1, 1)), axis=1
)
max_iter: int = 20
tol: np.float64 = np.float64(0.001)  # <-- 0,1 % de tolerancia

augmented_matrix

jacobi(augmented_matrix.copy(), tol, max_iter)
gauss_seidel(augmented_matrix.copy(), tol, max_iter)
relaxing(augmented_matrix.copy(), tol, max_iter, np.float64(1.12)) """

' example_matrix: NDArray = np.matrix(\n    [[6.0, -1.0, 3.0], [1.0, 3.0, 1.0], [3.0, -1.0, 5.0]], dtype=np.float64\n)\ntarget_values: NDArray = np.array([13.0, 10.0, 16.0], dtype=np.float64)\naugmented_matrix: NDArray = np.concatenate(\n    (example_matrix, target_values.reshape(-1, 1)), axis=1\n)\nmax_iter: int = 20\ntol: np.float64 = np.float64(0.001)  # <-- 0,1 % de tolerancia\n\naugmented_matrix\n\njacobi(augmented_matrix.copy(), tol, max_iter)\ngauss_seidel(augmented_matrix.copy(), tol, max_iter)\nrelaxing(augmented_matrix.copy(), tol, max_iter, np.float64(1.12)) '