# Projeto 2 de Métodos Numéricos I

## Importando os pacotes necessários

In [1]:
from methods.curve_adjusting import cubic_splines
from utils.parser import evaluate_one_variable
from numpy.typing import NDArray
from methods.derivative import *
from methods.integral import *
import numpy as np
import sympy as sy

## Exercício

Utilize interpolação polinomial por partes para obter uma aproximação para a função `f(x) = cos(πx)` no intervalo `[0, 1]`, considere as alternativas:
- Spline cúbico natural ou livre
- Spline fixado

Para ambos os casos:

In [2]:
func :str = "cos(pi * x)"

### a) Considere os seguintes pontos `x = 0; 0,25; 0,5; 0,75 e 1,0`

#### caso natural

In [3]:
x :NDArray[np.float64] = np.array([0.0, 0.25, 0.5, 0.75, 1.0], dtype=np.float64)
y :NDArray[np.float64] = np.array([evaluate_one_variable(func, el) for el in x], dtype=np.float64)

a, b, c, d = cubic_splines(x, y)

print("Os coeficientes de *a* são:\n", a, "\n")
print("Os coeficientes de *b* são:\n", b, "\n")
print("Os coeficientes de *c* são:\n", c, "\n")
print("Os coeficientes de *d* são:\n", d, "\n")

Os coeficientes de *a* são:
 [ 1.          0.70710678  0.         -0.70710678] 

Os coeficientes de *b* são:
 [-0.75735931 -2.         -3.24264069 -2.        ] 

Os coeficientes de *c* são:
 [ 0.         -4.97056275  0.          4.97056275] 

Os coeficientes de *d* são:
 [-6.627417  6.627417  6.627417 -6.627417] 



#### Caso fixado
Com:
- dx_0 = 2,0
- dx_n = 3,0

In [4]:
a, b, c, d = cubic_splines(x,
                           y,
                           dx_0=np.float64(2.0),
                           dx_n=np.float64(3.0))

print("Os coeficientes de *a* são:\n", a, "\n")
print("Os coeficientes de *b* são:\n", b, "\n")
print("Os coeficientes de *c* são:\n", c, "\n")
print("Os coeficientes de *d* são:\n", d, "\n")

Os coeficientes de *a* são:
 [ 1.          0.70710678  0.         -0.70710678] 

Os coeficientes de *b* são:
 [-1.04158551 -1.93154762 -3.23222402 -2.11011905] 

Os coeficientes de *c* são:
 [ 2.         -5.55984844  0.35714284  4.13127704] 

Os coeficientes de *d* são:
 [-10.07979791   7.8893217    5.03217893  -1.50836938] 



### b) Considere os seguintes pontos `x = 0; 0,125; 0,250; 0,375, 0,5; 0,625; 0,75; 0,875 e 1.0`

#### caso natural

In [5]:
x :NDArray[np.float64] = np.array([0.0, 0.125, 0.250, 0.375, 0.5, 0.75, 0.875, 1.0], dtype=np.float64)
y :NDArray[np.float64] = np.array([evaluate_one_variable(func, el) for el in x], dtype=np.float64)

a, b, c, d = cubic_splines(x, y)

print("Os coeficientes de *a* são:\n", a, "\n")
print("Os coeficientes de *b* são:\n", b, "\n")
print("Os coeficientes de *c* são:\n", c, "\n")
print("Os coeficientes de *d* são:\n", d, "\n")

Os coeficientes de *a* são:
 [ 1.          0.92387953  0.70710678  0.38268343  0.         -0.70710678
 -0.92387953] 

Os coeficientes de *b* são:
 [-0.36063827 -1.1056147  -2.2463402  -2.89773089 -3.13329899 -2.25883038
 -1.10204607] 

Os coeficientes de *c* são:
 [ 0.         -5.95981133 -3.1659927  -2.0451328   0.16058797  3.33728647
  5.91698801] 

Os coeficientes de *d* são:
 [-15.89283022   7.45018301   2.98895973   5.88192206   4.235598
   6.87920411 -15.77863469] 



#### Caso fixado
Com:
- dx_0 = 2,0
- dx_n = 3,0

In [6]:
a, b, c, d = cubic_splines(x,
                           y,
                           dx_0=np.float64(2.0),
                           dx_n=np.float64(3.0))

print("Os coeficientes de *a* são:\n", a, "\n")
print("Os coeficientes de *b* são:\n", b, "\n")
print("Os coeficientes de *c* são:\n", c, "\n")
print("Os coeficientes de *d* são:\n", d, "\n")

Os coeficientes de *a* são:
 [ 1.          0.92387953  0.70710678  0.38268343  0.         -0.70710678
 -0.92387953] 

Os coeficientes de *b* são:
 [-0.50501676 -1.06685769 -2.25698972 -2.89388987 -3.13801356 -2.23822507
 -1.16150474] 

Os coeficientes de *c* são:
 [ 2.         -6.4947276  -3.02632854 -2.06887272  0.11588323  3.48327072
  5.13049194] 

Os coeficientes de *d* são:
 [-22.65260693   9.24906417   2.55321552   5.82601587   4.48984998
   4.39258993  -5.68131185] 



### c) Para os itens `(a)` e `(b)`, integre o Spline no intervalo `[0, 1]` e compare com o valor exato da integral da função `f(x)`

#### Configurações e informações importantes

Sabemos que a integral analítica da função `f(x) = cos(π * x)` no intervalo `[0, 1]` é igual a `0`.

##### Salvando os limites do intervalo em variáveis

In [7]:
lower_bound :np.float64 = np.float64(0.0)
upper_bound :np.float64 = np.float64(1.0)

#### Pelo método do trapézio

In [8]:
trapezoid_integral(func,
                   lower_bound,
                   upper_bound)

np.float64(0.0)

#### Pelo método de Simpson 1/3

In [9]:
simpson13_integral(func,
                   lower_bound,
                   upper_bound)

np.float64(0.0)

#### Pelo método de Simpson 3/8

In [10]:
simpson38_integral(func,
                   lower_bound,
                   upper_bound)

np.float64(-8.326672684688674e-17)

#### Pelo método da quadratura de Gauss

In [11]:
gauss_quadrature(func,
                 lower_bound,
                 upper_bound,
                 2)

np.float64(-5.551115123125783e-17)

### d) Para os itens `(a)` e `(b)`, calcule as derivadas do Spline e obtenha uma aproximação de `f′(0,5)` e `f′′(0,5)` compare os resultados com os valores reais

#### Configurações e informações importantes

In [12]:
func :str = "cos(pi * x)"

Sabemos que a derivada analítica da função `f(x) = cos(π * x)` no ponto `0,5` é igual a `-π`.
- Ou seja, `f´(0,5) = -π`.

Sabemos que a segunda derivada analítica da função `f(x) = cos(π * x)` no ponto `0,5` é igual a `0`.
- Ou seja, `f´´(0,5) = 0`.

E sabemos que:

Original: `S_i(x) = a_i​ + b_i​(x−xi​) + c_i​(x−xi​)^2 + d_i​(x−xi​)^3`

Derivada: `S_i´(x) = b_i​ + 2 * c_i​(x−xi​) + 3 * d_i​(x−xi​)^2`

Segunda derivada: `S_i´´(x) = 2* c_i​ + 6 * d_i​(x−xi​)`

##### Derivada numérica de `0,5`

In [13]:
central_derivative_1(func,
                     np.float64(0.5),
                     np.float64(0.25))

np.float64(-3.104569499661587)

In [14]:
central_derivative_1(func,
                     np.float64(0.5),
                     np.float64(0.125))

np.float64(-3.1391475703122276)

##### Segunda derivada numérica de `0,5`

In [15]:
central_derivative_2(func,
                     np.float64(0.5),
                     np.float64(0.25))

np.float64(0.0)

In [16]:
central_derivative_2(func,
                     np.float64(0.5),
                     np.float64(0.125))

np.float64(1.7763568394002505e-15)

#### Resolução para a SPLine encontrada no item `a)`

Como o ponto `0,5` é o terceiro do SPLine, será escolhido o S_3, ou seja, `a[2]`, `b[2]`, `c[2]` e `d[2]`.

In [17]:
x :NDArray[np.float64] = np.array([0.0, 0.25, 0.5, 0.75, 1.0], dtype=np.float64)
y :NDArray[np.float64] = np.array([evaluate_one_variable(func, el) for el in x], dtype=np.float64)

order :int = 2

h :np.float64 = x[1] - x[0]
deriv_point :np.float64 = np.float64(0.5)

##### Caso natural

In [18]:
a, b, c, d = cubic_splines(x, y)

func_natural :str = f"({a[order]}) + \
({b[order]}) * (x - {x[order]}) + \
({c[order]}) * (x - {x[order]})**2 + \
({d[order]}) * (x - {x[order]})**3"

print(func_natural)
print("Derivada progressiva: ",
      progressive_derivative_1(func_natural,
                               deriv_point,
                               h)
      )
print("Derivada regressiva: ",
      regressive_derivative_1(func_natural,
                              deriv_point,
                              h)
      )
print("Derivada central: ",
      central_derivative_1(func_natural,
                           deriv_point,
                           h)
      )
print("Segunda derivada progressiva (utilizando a fórmula da função): ",
      progressive_derivative_2(func_natural,
                               deriv_point,
                               h)
      )
print("Segunda derivada regressiva (utilizando a fórmula da função): ",
      regressive_derivative_2(func_natural,
                              deriv_point,
                              h)
      )
print("Segunda derivada central (utilizando a fórmula da função): ",
      central_derivative_2(func_natural,
                           deriv_point,
                           h)
      )

func_natural = f"{b[order]} + \
2 * {c[order]} * (x - {x[order]}) + \
3 * {d[order]} * (x - {x[order]})**2"

print("Segunda derivada progressiva (utilizando a fórmula da derivada): ",
      progressive_derivative_2(func_natural,
                               deriv_point,
                               h)
      )
print("Segunda derivada regressiva (utilizando a fórmula da derivada): ",
      regressive_derivative_2(func_natural,
                              deriv_point,
                              h)
      )
print("Segunda derivada central (utilizando a fórmula da derivada): ",
      central_derivative_2(func_natural,
                           deriv_point,
                           h)
      )

(0.0) + (-3.2426406871192857) * (x - 0.5) + (0.0) * (x - 0.5)**2 + (6.627416997969523) * (x - 0.5)**3
Derivada progressiva:  -4.071067811865476
Derivada regressiva:  -4.071067811865476
Derivada central:  -3.242640687119286
Segunda derivada progressiva (utilizando a fórmula da função):  1.4210854715202004e-14
Segunda derivada regressiva (utilizando a fórmula da função):  -1.1546319456101628e-14
Segunda derivada central (utilizando a fórmula da função):  -4.440892098500626e-16
Segunda derivada progressiva (utilizando a fórmula da derivada):  39.76450198781714
Segunda derivada regressiva (utilizando a fórmula da derivada):  39.76450198781713
Segunda derivada central (utilizando a fórmula da derivada):  39.76450198781715


##### Caso fixado

In [19]:
a, b, c, d = cubic_splines(x,
                           y,
                           dx_0=progressive_derivative_1(func, x[0], h),
                           dx_n=regressive_derivative_1(func, x[-1], h))

func_fixed :str = f"({a[order]}) + \
({b[order]}) * (x - {x[order]}) + \
({c[order]}) * (x - {x[order]})**2 + \
({d[order]}) * (x - {x[order]})**3"

print(func_fixed)
print("Derivada progressiva: ",
      progressive_derivative_1(func_fixed,
                               deriv_point,
                               h)
      )
print("Derivada regressiva: ",
      regressive_derivative_1(func_fixed,
                              deriv_point,
                              h)
      )
print("Derivada central: ",
      central_derivative_1(func_fixed,
                           deriv_point,
                           h)
      )
print("Segunda derivada progressiva (utilizando a fórmula da função): ",
      progressive_derivative_2(func_fixed,
                               deriv_point,
                               h)
      )
print("Segunda derivada regressiva (utilizando a fórmula da função): ",
      regressive_derivative_2(func_fixed,
                              deriv_point,
                              h)
      )
print("Segunda derivada central (utilizando a fórmula da função): ",
      central_derivative_2(func_fixed,
                           deriv_point,
                           h)
      )

func_natural = f"{b[order]} + \
2 * {c[order]} * (x - {x[order]}) + \
3 * {d[order]} * (x - {x[order]})**2"

print("Segunda derivada progressiva (utilizando a fórmula da derivada): ",
      progressive_derivative_2(func_fixed,
                               deriv_point,
                               h)
      )
print("Segunda derivada regressiva (utilizando a fórmula da derivada): ",
      regressive_derivative_2(func_fixed,
                              deriv_point,
                              h)
      )
print("Segunda derivada central (utilizando a fórmula da derivada): ",
      central_derivative_2(func_fixed,
                           deriv_point,
                           h)
      )

(0.0) + (-3.2426406890367616) * (x - 0.5) + (-0.049020808352679524) * (x - 0.5)**2 + (6.823500262059863) * (x - 0.5)**3
Derivada progressiva:  -4.095578221794244
Derivada regressiva:  -4.095578221794244
Derivada central:  -3.2426406890367616
Segunda derivada progressiva (utilizando a fórmula da função):  -0.09804161670536615
Segunda derivada regressiva (utilizando a fórmula da função):  -0.09804161670535283
Segunda derivada central (utilizando a fórmula da função):  -0.09804161670535964
Segunda derivada progressiva (utilizando a fórmula da derivada):  -0.09804161670536615
Segunda derivada regressiva (utilizando a fórmula da derivada):  -0.09804161670535283
Segunda derivada central (utilizando a fórmula da derivada):  -0.09804161670535964


#### Resolução para a SPLine encontrada no item `b)`

Como o ponto `0,5` é o terceiro do SPLine, será escolhido o S_5, ou seja, `a[4]`, `b[4]`, `c[4]` e `d[4]`.

In [20]:
x :NDArray[np.float64] = np.array([0.0, 0.125, 0.250, 0.375, 0.5, 0.75, 0.875, 1.0], dtype=np.float64)
y :NDArray[np.float64] = np.array([evaluate_one_variable(func, el) for el in x], dtype=np.float64)

order :int = 4

h :np.float64 = x[1] - x[0]
deriv_point :np.float64 = np.float64(0.5)

##### Caso natural

In [21]:
a, b, c, d = cubic_splines(x, y)

func_natural :str = f"({a[order]}) + \
({b[order]}) * (x - {x[order]}) + \
({c[order]}) * (x - {x[order]})**2 + \
({d[order]}) * (x - {x[order]})**3"

print(func_natural)
print("Derivada progressiva: ",
      progressive_derivative_1(func_natural,
                               deriv_point,
                               h)
      )
print("Derivada regressiva: ",
      regressive_derivative_1(func_natural,
                              deriv_point,
                              h)
      )
print("Derivada central: ",
      central_derivative_1(func_natural,
                           deriv_point,
                           h)
      )
print("Segunda derivada progressiva (utilizando a fórmula da função): ",
      progressive_derivative_2(func_natural,
                               deriv_point,
                               h)
      )
print("Segunda derivada regressiva (utilizando a fórmula da função): ",
      regressive_derivative_2(func_natural,
                              deriv_point,
                              h)
      )
print("Segunda derivada central (utilizando a fórmula da função): ",
      central_derivative_2(func_natural,
                           deriv_point,
                           h)
      )

func_natural = f"{b[order]} + \
2 * {c[order]} * (x - {x[order]}) + \
3 * {d[order]} * (x - {x[order]})**2"

print("Segunda derivada progressiva (utilizando a fórmula da derivada): ",
      progressive_derivative_2(func_natural,
                               deriv_point,
                               h)
      )
print("Segunda derivada regressiva (utilizando a fórmula da derivada): ",
      regressive_derivative_2(func_natural,
                              deriv_point,
                              h)
      )
print("Segunda derivada central (utilizando a fórmula da derivada): ",
      central_derivative_2(func_natural,
                           deriv_point,
                           h)
      )

(0.0) + (-3.1332989918598746) * (x - 0.5) + (0.1605879690525298) * (x - 0.5)**2 + (4.235597997608831) * (x - 0.5)**3
Derivada progressiva:  -3.2656614292851507
Derivada regressiva:  -3.2656614292851502
Derivada central:  -3.133298991859874
Segunda derivada progressiva (utilizando a fórmula da função):  0.32117593810505696
Segunda derivada regressiva (utilizando a fórmula da função):  0.32117593810505696
Segunda derivada central (utilizando a fórmula da função):  0.3211759381050581
Segunda derivada progressiva (utilizando a fórmula da derivada):  25.41358798565301
Segunda derivada regressiva (utilizando a fórmula da derivada):  25.413587985653066
Segunda derivada central (utilizando a fórmula da derivada):  25.41358798565297


##### Caso fixado

In [22]:
a, b, c, d = cubic_splines(x,
                           y,
                           dx_0=progressive_derivative_1(func, x[0], h),
                           dx_n=regressive_derivative_1(func, x[-1], h))

func_fixed :str = f"({a[order]}) + \
({b[order]}) * (x - {x[order]}) + \
({c[order]}) * (x - {x[order]})**2 + \
({d[order]}) * (x - {x[order]})**3"

print(func_fixed)
print("Derivada progressiva: ",
      progressive_derivative_1(func_fixed,
                               deriv_point,
                               h)
      )
print("Derivada regressiva: ",
      regressive_derivative_1(func_fixed,
                              deriv_point,
                              h)
      )
print("Derivada central: ",
      central_derivative_1(func_fixed,
                           deriv_point,
                           h)
      )
print("Segunda derivada progressiva (utilizando a fórmula da função): ",
      progressive_derivative_2(func_fixed,
                               deriv_point,
                               h)
      )
print("Segunda derivada regressiva (utilizando a fórmula da função): ",
      regressive_derivative_2(func_fixed,
                              deriv_point,
                              h)
      )
print("Segunda derivada central (utilizando a fórmula da função): ",
      central_derivative_2(func_fixed,
                           deriv_point,
                           h)
      )

func_natural = f"{b[order]} + \
2 * {c[order]} * (x - {x[order]}) + \
3 * {d[order]} * (x - {x[order]})**2"

print("Segunda derivada progressiva (utilizando a fórmula da derivada): ",
      progressive_derivative_2(func_fixed,
                               deriv_point,
                               h)
      )
print("Segunda derivada regressiva (utilizando a fórmula da derivada): ",
      regressive_derivative_2(func_fixed,
                              deriv_point,
                              h)
      )
print("Segunda derivada central (utilizando a fórmula da derivada): ",
      central_derivative_2(func_fixed,
                           deriv_point,
                           h)
      )

(0.0) + (-3.1332186003555194) * (x - 0.5) + (0.16122393037905644) * (x - 0.5)**2 + (4.23176788823304) * (x - 0.5)**3
Derivada progressiva:  -3.265461346862802
Derivada regressiva:  -3.2654613468628018
Derivada central:  -3.1332186003555194
Segunda derivada progressiva (utilizando a fórmula da função):  0.3224478607581176
Segunda derivada regressiva (utilizando a fórmula da função):  0.3224478607581034
Segunda derivada central (utilizando a fórmula da função):  0.32244786075811166
Segunda derivada progressiva (utilizando a fórmula da derivada):  0.3224478607581176
Segunda derivada regressiva (utilizando a fórmula da derivada):  0.3224478607581034
Segunda derivada central (utilizando a fórmula da derivada):  0.32244786075811166


### e) Baseado nos resultados de `(c)` e `(d)` qual aproxima ̧c ̃ao por Splines oferece melhores resultados. Justifique.