# Projeto 2 de Métodos Numéricos I

## Importando os pacotes necessários

In [1]:
from methods.curve_adjusting import cubic_splines, get_spline_func_str
from utils.parser import evaluate_one_variable, get_derivative
from numpy.typing import NDArray
import numpy as np
import pandas as pd
from scipy.integrate import quad

## Exercício

Utilize interpolação polinomial por partes para obter uma aproximação para a função `f(x) = cos(πx)` no intervalo `[0, 1]`, considere as alternativas:
- Spline cúbico natural ou livre
- Spline fixado

Para ambos os casos:

In [2]:
func :str = "cos(pi * x)"
derivative_func = get_derivative(func)

### a) Considere os seguintes pontos `x = 0; 0,25; 0,5; 0,75 e 1,0`

#### caso natural

In [3]:
x_a :NDArray[np.float64] = np.array([0.0, 0.25, 0.5, 0.75, 1.0], dtype=np.float64)
y_a :NDArray[np.float64] = np.array([evaluate_one_variable(func, el) for el in x_a], dtype=np.float64)

natural_coef_a = cubic_splines(x_a, y_a)
a, b, c, d = natural_coef_a

print("Os coeficientes de *a* são:\n", a, "\n")
print("Os coeficientes de *b* são:\n", b, "\n")
print("Os coeficientes de *c* são:\n", c, "\n")
print("Os coeficientes de *d* são:\n", d, "\n")

Os coeficientes de *a* são:
 [ 1.          0.70710678  0.         -0.70710678] 

Os coeficientes de *b* são:
 [-0.75735931 -2.         -3.24264069 -2.        ] 

Os coeficientes de *c* são:
 [ 0.         -4.97056275  0.          4.97056275] 

Os coeficientes de *d* são:
 [-6.627417  6.627417  6.627417 -6.627417] 



#### Caso fixado

In [4]:
fixed_coef_a = cubic_splines(x_a,
                           y_a,
                           dx_0= derivative_func(x_a[0]),
                           dx_n=derivative_func(x_a[-1]))
a, b, c, d = fixed_coef_a

print("Os coeficientes de *a* são:\n", a, "\n")
print("Os coeficientes de *b* são:\n", b, "\n")
print("Os coeficientes de *c* são:\n", c, "\n")
print("Os coeficientes de *d* são:\n", d, "\n")

Os coeficientes de *a* são:
 [ 1.          0.70710678  0.         -0.70710678] 

Os coeficientes de *b* são:
 [-4.00913789e-08 -2.21638836e+00 -3.13444651e+00 -2.21638837e+00] 

Os coeficientes de *c* são:
 [-5.19332068e+00 -3.67223266e+00  8.04211141e-08  3.67223246e+00] 

Os coeficientes de *d* são:
 [2.02811736 4.89631032 4.89630984 2.02811809] 



### b) Considere os seguintes pontos `x = 0; 0,125; 0,250; 0,375, 0,5; 0,625; 0,75; 0,875 e 1.0`

#### caso natural

In [5]:
x_b :NDArray[np.float64] = np.array([0.0, 0.125, 0.250, 0.375, 0.5, 0.625, 0.75, 0.875, 1.0], dtype=np.float64)
y_b :NDArray[np.float64] = np.array([evaluate_one_variable(func, el) for el in x_b], dtype=np.float64)

natural_coef_b = cubic_splines(x_b, y_b)
a, b, c, d = natural_coef_b

print("Os coeficientes de *a* são:\n", a, "\n")
print("Os coeficientes de *b* são:\n", b, "\n")
print("Os coeficientes de *c* são:\n", c, "\n")
print("Os coeficientes de *d* são:\n", d, "\n")

Os coeficientes de *a* são:
 [ 1.          0.92387953  0.70710678  0.38268343  0.         -0.38268343
 -0.70710678 -0.92387953] 

Os coeficientes de *b* são:
 [-0.36075774 -1.10537572 -2.2471766  -2.89462427 -3.14488905 -2.89462427
 -2.2471766  -1.10537573] 

Os coeficientes de *c* são:
 [ 0.00000000e+00 -5.95694389e+00 -3.17746312e+00 -2.00211825e+00
  1.46244483e-08  2.00211821e+00  3.17746317e+00  5.95694383e+00] 

Os coeficientes de *d* são:
 [-15.88518372   7.41194874   3.13425298   5.33898203   5.33898186
   3.13425322   7.41194843 -15.88518355] 



#### Caso fixado

In [6]:
fixed_coef_b = cubic_splines(x_b,
                           y_b,
                           dx_0=derivative_func(x_b[0]),
                           dx_n=derivative_func(x_b[-1]))

a, b, c, d = fixed_coef_b

print("Os coeficientes de *a* são:\n", a, "\n")
print("Os coeficientes de *b* são:\n", b, "\n")
print("Os coeficientes de *c* são:\n", c, "\n")
print("Os coeficientes de *d* são:\n", d, "\n")

Os coeficientes de *a* são:
 [ 1.          0.92387953  0.70710678  0.38268343  0.         -0.38268343
 -0.70710678 -0.92387953] 

Os coeficientes de *b* são:
 [-2.13395612e-08 -1.20207367e+00 -2.22114254e+00 -2.90206257e+00
 -3.14116990e+00 -2.90206258e+00 -2.22114254e+00 -1.20207368e+00] 

Os coeficientes de *c* são:
 [-4.99853997e+00 -4.61804931e+00 -3.53450163e+00 -1.91285865e+00
  4.63957316e-08  1.91285854e+00  3.53450178e+00  4.61804909e+00] 

Os coeficientes de *d* são:
 [1.01464176 2.88946046 4.3243813  5.10095652 5.10095599 4.32438195
 2.88945951 1.0146433 ] 



### c) Para os itens `(a)` e `(b)`, integre o Spline no intervalo `[0, 1]` e compare com o valor exato da integral da função `f(x)`

Sabemos que a integral analítica da função `f(x) = cos(π * x)` no intervalo `[0, 1]` é igual a `0`.

In [7]:
def get_spline_funcs_integral(x, a, b, c, d):
    integrals = []

    for i in range(len(x) - 1):
        integral, _ = quad(lambda t: a[i] + b[i] * (t - x[i]) + c[i] * (t - x[i]) ** 2 + d[i] * (t - x[i]) ** 3,
                        x[i], x[i + 1])
        integrals.append(integral)

    return np.array(integrals, dtype=np.float64)

#### Resolução para a Spline encontrada no item `a)`

In [8]:
natural_integral_a = get_spline_funcs_integral(x_a, *natural_coef_a)
fixed_integral_a = get_spline_funcs_integral(x_a, *fixed_coef_a)

print("Valores das integrais do spline natural:\n", natural_integral_a, "\n")
print("Valores das integrais do spline fixo:\n", fixed_integral_a, "\n")


print("Soma das integrais do spline natural:\n", natural_integral_a.sum(), "\n"
      "Soma das integrais do spline fixo:\n", fixed_integral_a.sum(), "\n")

natural_integral_error_a = abs(0 - natural_integral_a.sum())
fixed_integral_error_a = abs(0 - fixed_integral_a.sum())

print("Erro da integral do spline natural:\n", natural_integral_error_a, "\n")
print("Erro da integral do spline fixo:\n", fixed_integral_error_a, "\n")

Valores das integrais do spline natural:
 [ 0.21986043  0.09486043 -0.09486043 -0.21986043] 

Valores das integrais do spline fixo:
 [ 0.22493204  0.0931699  -0.0931699  -0.22493204] 

Soma das integrais do spline natural:
 0.0 
Soma das integrais do spline fixo:
 -1.303118168927142e-10 

Erro da integral do spline natural:
 0.0 

Erro da integral do spline fixo:
 1.303118168927142e-10 



#### Resolução para a Spline encontrada no item `b)`

In [9]:
natural_integral_b = get_spline_funcs_integral(x_b, *natural_coef_b)
fixed_integral_b = get_spline_funcs_integral(x_b, *fixed_coef_b)

print("Valores das integrais do spline natural:\n", natural_integral_b, "\n")
print("Valores das integrais do spline fixo:\n", fixed_integral_b, "\n")


print("Soma das integrais do spline natural:\n", natural_integral_b.sum(), "\n"
      "Soma das integrais do spline fixo:\n", fixed_integral_b.sum(), "\n")

natural_integral_error_b = abs(0 - natural_integral_b.sum())
fixed_integral_error_b = abs(0 - fixed_integral_b.sum())

print("Erro da integral do spline natural:\n", natural_integral_error_b, "\n")
print("Erro da integral do spline fixo:\n", fixed_integral_error_b, "\n")

Valores das integrais do spline natural:
 [ 0.12121203  0.10342336  0.06895492  0.02424358 -0.02424358 -0.06895492
 -0.10342336 -0.12121203] 

Valores das integrais do spline fixo:
 [ 0.12180767  0.10326356  0.0689985   0.02422905 -0.02422905 -0.0689985
 -0.10326356 -0.12180767] 

Soma das integrais do spline natural:
 9.85966863709109e-12 
Soma das integrais do spline fixo:
 -1.6460721674604883e-11 

Erro da integral do spline natural:
 9.85966863709109e-12 

Erro da integral do spline fixo:
 1.6460721674604883e-11 



### d) Para os itens `(a)` e `(b)`, calcule as derivadas do Spline e obtenha uma aproximação de `f′(0,5)` e `f′′(0,5)` compare os resultados com os valores reais

Sabemos que a derivada analítica da função `f(x) = cos(π * x)` no ponto `0,5` é igual a `-π`.
- Ou seja, `f´(0,5) = -π`.

Sabemos que a segunda derivada analítica da função `f(x) = cos(π * x)` no ponto `0,5` é igual a `0`.
- Ou seja, `f´´(0,5) = 0`.

E sabemos que:

Original: `S_i(x) = a_i​ + b_i​(x−xi​) + c_i​(x−xi​)^2 + d_i​(x−xi​)^3`

Derivada: `S_i´(x) = b_i​ + 2 * c_i​(x−xi​) + 3 * d_i​(x−xi​)^2`

Segunda derivada: `S_i´´(x) = 2* c_i​ + 6 * d_i​(x−xi​)`

#### Caso natural

##### Item `a)`

In [10]:
# Caso natural - item a)
spline_func_0_5_a = get_spline_func_str(0.5, *natural_coef_a, x_a)
derivative_func = get_derivative(spline_func_0_5_a, degree=1)
derivative_func_2 = get_derivative(spline_func_0_5_a, degree=2)

print("=== SPLINE NATURAL - ITEM A ===")
print("A função do spline natural no ponto 0.5 é:\n", spline_func_0_5_a, "\n")

# Avaliação das derivadas
f_prime_05_natural_a = derivative_func(0.5)
f_double_prime_05_natural_a = derivative_func_2(0.5)

print("Valores calculados:")
print(f"S'(0.5) = {f_prime_05_natural_a:.15f}")
print(f"S''(0.5) = {f_double_prime_05_natural_a:.15f}")

# Comparação com valores exatos
exact_f_prime_05 = -np.pi
exact_f_double_prime_05 = 0.0
natural_derivative_error_a = abs(exact_f_prime_05 - f_prime_05_natural_a)
natural_double_derivative_error_a = abs(exact_f_double_prime_05 - f_double_prime_05_natural_a)

print("\nComparação com valores exatos:")
print(f"f'(0.5) exato = {exact_f_prime_05:.15f}")
print(f"f'(0.5) spline = {f_prime_05_natural_a:.15f}")
print(f"Erro absoluto f' = {natural_derivative_error_a:.15f}")

print(f"f''(0.5) exato = {exact_f_double_prime_05:.15f}")
print(f"f''(0.5) spline = {f_double_prime_05_natural_a:.15f}")
print(f"Erro absoluto f'' = {natural_double_derivative_error_a:.15f}")

=== SPLINE NATURAL - ITEM A ===
A função do spline natural no ponto 0.5 é:
 (0.7071067811865476 + -2.0 * (x - 0.25) + -4.970562748477143 * (x - 0.25)**2 + 6.627416997969523 * (x - 0.25)**3) 

Valores calculados:
S'(0.5) = -3.242640687119286
S''(0.5) = 0.000000000000000

Comparação com valores exatos:
f'(0.5) exato = -3.141592653589793
f'(0.5) spline = -3.242640687119286
Erro absoluto f' = 0.101048033529493
f''(0.5) exato = 0.000000000000000
f''(0.5) spline = 0.000000000000000
Erro absoluto f'' = 0.000000000000000


##### Item `b)`

In [11]:
# Caso natural - item a)
spline_func_0_5_b = get_spline_func_str(0.5, *natural_coef_b, x_b)
derivative_func = get_derivative(spline_func_0_5_b, degree=1)
derivative_func_2 = get_derivative(spline_func_0_5_b, degree=2)

print("=== SPLINE NATURAL - ITEM B ===")
print("A função do spline natural no ponto 0.5 é:\n", spline_func_0_5_b, "\n")

# Avaliação das derivadas
f_prime_05_natural_b = derivative_func(0.5)
f_double_prime_05_natural_b = derivative_func_2(0.5)

print("Valores calculados:")
print(f"S'(0.5) = {f_prime_05_natural_b:.15f}")
print(f"S''(0.5) = {f_double_prime_05_natural_b:.15f}")

# Comparação com valores exatos
exact_f_prime_05 = -np.pi
exact_f_double_prime_05 = 0.0
natural_derivative_error_b = abs(exact_f_prime_05 - f_prime_05_natural_b)
natural_double_derivative_error_b = abs(exact_f_double_prime_05 - f_double_prime_05_natural_b)

print("\nComparação com valores exatos:")
print(f"f'(0.5) exato = {exact_f_prime_05:.15f}")
print(f"f'(0.5) spline = {f_prime_05_natural_b:.15f}")
print(f"Erro absoluto f' = {natural_derivative_error_b:.15f}")

print(f"f''(0.5) exato = {exact_f_double_prime_05:.15f}")
print(f"f''(0.5) spline = {f_double_prime_05_natural_b:.15f}")
print(f"Erro absoluto f'' = {natural_double_derivative_error_b:.15f}")

=== SPLINE NATURAL - ITEM B ===
A função do spline natural no ponto 0.5 é:
 (0.3826834323650898 + -2.894624272187673 * (x - 0.375) + -2.0021182481087676 * (x - 0.375)**2 + 5.338982033955243 * (x - 0.375)**3) 

Valores calculados:
S'(0.5) = -3.144889051373213
S''(0.5) = 0.000000029248898

Comparação com valores exatos:
f'(0.5) exato = -3.141592653589793
f'(0.5) spline = -3.144889051373213
Erro absoluto f' = 0.003296397783420
f''(0.5) exato = 0.000000000000000
f''(0.5) spline = 0.000000029248898
Erro absoluto f'' = 0.000000029248898


#### Caso fixado

##### Item `a)`

In [12]:
# Caso fixo - item a)
spline_func_0_5_a = get_spline_func_str(0.5, *fixed_coef_a, x_a)
derivative_func = get_derivative(spline_func_0_5_a, degree=1)
derivative_func_2 = get_derivative(spline_func_0_5_a, degree=2)

print("=== SPLINE FIXO - ITEM A ===")
print("A função do spline fixo no ponto 0.5 é:\n", spline_func_0_5_a, "\n")

# Avaliação das derivadas
f_prime_05_fixed_a = derivative_func(0.5)
f_double_prime_05_fixed_a = derivative_func_2(0.5)

print("Valores calculados:")
print(f"S'(0.5) = {f_prime_05_fixed_a:.15f}")
print(f"S''(0.5) = {f_double_prime_05_fixed_a:.15f}")

# Comparação com valores exatos
exact_f_prime_05 = -np.pi
exact_f_double_prime_05 = 0.0
fixed_derivative_error_a = abs(exact_f_prime_05 - f_prime_05_fixed_a)
fixed_double_derivative_error_a = abs(exact_f_double_prime_05 - f_double_prime_05_fixed_a)

print("\nComparação com valores exatos:")
print(f"f'(0.5) exato = {exact_f_prime_05:.15f}")
print(f"f'(0.5) spline = {f_prime_05_fixed_a:.15f}")
print(f"Erro absoluto f' = {fixed_derivative_error_a:.15f}")

print(f"f''(0.5) exato = {exact_f_double_prime_05:.15f}")
print(f"f''(0.5) spline = {f_double_prime_05_fixed_a:.15f}")
print(f"Erro absoluto f'' = {fixed_double_derivative_error_a:.15f}")

=== SPLINE FIXO - ITEM A ===
A função do spline fixo no ponto 0.5 é:
 (0.7071067811865476 + -2.2163883550375476 * (x - 0.25) + -3.6722326584624123 * (x - 0.25)**2 + 4.896310318511369 * (x - 0.25)**3) 

Valores calculados:
S'(0.5) = -3.134446499547872
S''(0.5) = 0.000000160842227

Comparação com valores exatos:
f'(0.5) exato = -3.141592653589793
f'(0.5) spline = -3.134446499547872
Erro absoluto f' = 0.007146154041921
f''(0.5) exato = 0.000000000000000
f''(0.5) spline = 0.000000160842227
Erro absoluto f'' = 0.000000160842227


##### Item `b)`

In [13]:
# Caso fixo - item b)
spline_func_0_5_b = get_spline_func_str(0.5, *fixed_coef_b, x_b)
derivative_func = get_derivative(spline_func_0_5_b, degree=1)
derivative_func_2 = get_derivative(spline_func_0_5_b, degree=2)

print("=== SPLINE FIXO - ITEM B ===")
print("A função do spline fixo no ponto 0.5 é:\n", spline_func_0_5_b, "\n")

# Avaliação das derivadas
f_prime_05_fixed_b = derivative_func(0.5)
f_double_prime_05_fixed_b = derivative_func_2(0.5)

print("Valores calculados:")
print(f"S'(0.5) = {f_prime_05_fixed_b:.15f}")
print(f"S''(0.5) = {f_double_prime_05_fixed_b:.15f}")

# Comparação com valores exatos
exact_f_prime_05 = -np.pi
exact_f_double_prime_05 = 0.0
fixed_derivative_error_b = abs(exact_f_prime_05 - f_prime_05_fixed_b)
fixed_double_derivative_error_b = abs(exact_f_double_prime_05 - f_double_prime_05_fixed_b)

print("\nComparação com valores exatos:")
print(f"f'(0.5) exato = {exact_f_prime_05:.15f}")
print(f"f'(0.5) spline = {f_prime_05_fixed_b:.15f}")
print(f"Erro absoluto f' = {fixed_derivative_error_b:.15f}")

print(f"f''(0.5) exato = {exact_f_double_prime_05:.15f}")
print(f"f''(0.5) spline = {f_double_prime_05_fixed_b:.15f}")
print(f"Erro absoluto f'' = {fixed_double_derivative_error_b:.15f}")

=== SPLINE FIXO - ITEM B ===
A função do spline fixo no ponto 0.5 é:
 (0.3826834323650898 + -2.902062573541427 * (x - 0.375) + -1.9128586477493597 * (x - 0.375)**2 + 5.100956517720243 * (x - 0.375)**3) 

Valores calculados:
S'(0.5) = -3.141169898710630
S''(0.5) = 0.000000092791465

Comparação com valores exatos:
f'(0.5) exato = -3.141592653589793
f'(0.5) spline = -3.141169898710630
Erro absoluto f' = 0.000422754879163
f''(0.5) exato = 0.000000000000000
f''(0.5) spline = 0.000000092791465
Erro absoluto f'' = 0.000000092791465


### e) Baseado nos resultados de `(c)` e `(d)` qual aproximação por Splines oferece melhores resultados. Justifique.

#### Erros dos métodos na integração

In [16]:
integral_errors = np.array([
    natural_integral_error_a,
    fixed_integral_error_a,
    natural_integral_error_b,
    fixed_integral_error_b
])
integral_methods = [
    "Natural Spline (a)",
    "Fixed Spline (a)",
    "Natural Spline (b)",
    "Fixed Spline (b)"
]

df_integral = pd.DataFrame({
    "Method": integral_methods,
    "Integral Error": integral_errors
})

df_integral

Method  Integral Error
0  Natural Spline (a)    0.000000e+00
1    Fixed Spline (a)    1.303118e-10
2  Natural Spline (b)    9.859669e-12
3    Fixed Spline (b)    1.646072e-11

#### Erros dos métodos na derivação

In [15]:
# DataFrame apenas para erros das derivadas
derivative_errors = np.array([
    natural_derivative_error_a,
    fixed_derivative_error_a,
    natural_derivative_error_b,
    fixed_derivative_error_b
], dtype=np.float64)

double_derivative_errors = np.array([
    natural_double_derivative_error_a,
    fixed_double_derivative_error_a,
    natural_double_derivative_error_b,
    fixed_double_derivative_error_b
], dtype=np.float64)

derivative_methods = [
    "Natural Spline (a)",
    "Fixed Spline (a)",
    "Natural Spline (b)",
    "Fixed Spline (b)"
]

df_derivatives = pd.DataFrame({
    "Method": derivative_methods,
    "f'(0.5) Error": derivative_errors,
    "f''(0.5) Error": double_derivative_errors
})

# Definindo tipos das colunas
df_derivatives = df_derivatives.astype({
    'Method': 'string',
    "f'(0.5) Error": 'float64',
    "f''(0.5) Error": 'float64'
})

df_derivatives

Method  f'(0.5) Error  f''(0.5) Error
0  Natural Spline (a)       0.101048    0.000000e+00
1    Fixed Spline (a)       0.007146    1.608422e-07
2  Natural Spline (b)       0.003296    2.924890e-08
3    Fixed Spline (b)       0.000423    9.279147e-08