# Notebook de testes

## Importando os pacotes

In [1]:
from methods.curve_adjusting import natural_splines
from methods.polynomial_interpolation import *
from utils.parser import evaluate_one_variable
from numpy.typing import NDArray
import numpy as np
import sympy as sy

## Dados para testes

In [2]:
func:str = "1/x"
degree:int = 2
points:NDArray = np.array([2, 2.5, 4], dtype=np.float64)
pointwise_matrix:NDArray = np.array([points,
                                     [evaluate_one_variable(func, point) for point in points]],
                                    dtype=np.float64)
print("pontos x: ", pointwise_matrix[0, :])
print("pontos f(x): ", pointwise_matrix[1, :])

pontos x:  [2.  2.5 4. ]
pontos f(x):  [0.5  0.4  0.25]


## Newton

In [3]:
newton_interpolation(pointwise_matrix, np.float64(2.2))

(np.float64(0.45699999999999996), array([0.04 , 0.003]))

## Lagrange

In [4]:
estimate_points:NDArray = np.array([2.2, 3.5], dtype=np.float64)

for point in estimate_points:
    print(point, " :: ", lagrange_interpolation(pointwise_matrix, point), end="\n")

2.2  ::  0.45699999999999996
3.5  ::  0.275


## SPLines

In [5]:
natural_splines(
    np.array([0, 1, 2, 3], dtype=np.float64),
    np.array([1, np.e, np.e**2, np.e**3], dtype=np.float64)
)

Vetor h
 [1. 1. 1.]
Matriz A
 [[1. 0. 0. 0.]
 [1. 4. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]]
Matriz B
 [0.         5.01232281 0.         0.        ]


ValueError: Elemento nulo encontrado na diagonal.