In [1]:
from methods.polynomial_regression import create_augmented_matrix, retrieve_poly_coef
from methods.multiple_regression import determinate_elements, retrieve_multiple_coef
from methods.linear_regression import linear_regression
from numpy.typing import NDArray
import numpy as np

In [2]:
x :NDArray = np.array(list(range(10)), dtype=np.float64)
y :NDArray = np.array([2, 4, 6, 1, 3, 5, 8, 10, 1, 9], dtype=np.float64)

In [3]:
a0, a1, erro_padrao_estimativa, r2 = linear_regression(x, y)
print("Coeficiente linear: ", a0)
print("Coeficiente angular: ", a1)
print("Erro padrão da estimativa: ", erro_padrao_estimativa)
print("Coeficiente de determinação: ", r2)

Coeficiente linear:  2.581818181818182
Coeficiente angular:  0.5151515151515151
Erro padrão da estimativa:  3.0619858875830204
Coeficiente de determinação:  0.23851715120750644


In [4]:
x = np.array([1, 2, 3], dtype=np.float64)
y = np.array([3, 6, 9], dtype=np.float64)
grau :int = 2
matriz_aumentada :NDArray = create_augmented_matrix(x, y, grau)
A :NDArray = matriz_aumentada[:, :-1]
b :NDArray = matriz_aumentada[:, -1]
print("A:\n", A)
print("b:\n", b)

A:
 [[13.  0.  0.]
 [13. 10.  0.]
 [13. 10.  5.]]
b:
 [ 18.  42. 108.]


In [5]:
print("Os coeficientes são:\n", retrieve_poly_coef(A, b))

Os coeficientes são:
 [ 1.38461538  2.4        13.2       ]


In [6]:
x = np.array([[1.0, 2.0],
              [2.0, 3.0],
              [3.0, 4.0],
              [4.0, 5.0]],
             dtype=np.float64)
y = np.array([5.0, 7.0, 9.0, 11.0],
             dtype=np.float64)
matriz_aumentada = determinate_elements(x, y)
A = matriz_aumentada[:, :-1]
b = matriz_aumentada[:, -1]

In [7]:
print("Os coeficientes são:\n", retrieve_multiple_coef(A, b))

LinAlgError: Singular matrix